name: Grain NEAR SDK CI Workflow
on: [push, pull_request]

jobs:
  build:
    name: Test
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        node-version: ["16"]
        grain-version: ["v0.5.11"]

    steps:
      - name: Checkout project
        uses: actions/checkout@v3.1.0

      - name: Setup Node.js
        uses: actions/setup-node@v3.5.1
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true
          cache: "npm"

      # Install specific version of npm
      - name: Setup npm 8.4.0
        run: |
          npm install -g npm@8.4.0

      - name: Install Grain
        uses: engineerd/configurator@v0.0.8
        with:
          name: grain
          url: https://github.com/grain-lang/grain/releases/download/grain-${{ matrix.grain-version }}/grain-linux-x64

      - name: Install dependencies
        run: |
          npm ci && cd test-suite && npm ci && cd example-contracts && npm ci

      - name: Run the tests
        run: |
          npm test
